" Install pathogen
call pathogen#infect()

map <Leader><Leader>[ :bp<CR>
map <Leader><Leader>] :bn<CR>

map ,t :CtrlP<CR>
map ,b <Leader>b
map ,a :A<CR>

map <Leader>r :e %:p:h
nmap ,r :e %:p:h
nmap rr :!rspec %<CR>

map ,1 :!!!<CR>

" Turn on filetype and indentation rules on
filetype indent on
filetype plugin on

" General settings
set title
set encoding=utf-8

set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

set hidden " Not sure what this does...

" Disable backups
set nobackup
set nowritebackup
set noswapfile

" Ignores Gone Wild!
set wildignore+=*/.git/*,*/.sass-cache/*
set wildignore+=*.png,*.gif,*.jpg,*.ico,*.pdf,*.DS_Store

" CTRLP ignores
" let g:ctrlp_use_caching = 0  " Disable caching
let g:ctrlp_custom_ignore = {
  \ 'dir':  'coverage\|tmp\|log\|solr',
  \ 'file': '\.exe$\|\.so$\|\.dll$|\.gif$\|\.png$\|\.jpg$|\.ico$|\.ttf$|\.EOT$|\.ico$\|\.DS_Store$',
  \ }

" Quicky exit edit mode with jj
imap jj <Esc>:w<CR>
imap kk <Esc>:wq<CR>

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Viewing
set number
set ruler
set cursorline
set nowrap
set list listchars=tab:\ \ ,trail:·
set nofoldenable
set ruler
set showcmd
set laststatus=2
syntax enable
