# Note for OS X El Capitan Users
##
# OS X El Capitan (10.11) calls path_helper from /etc/zprofile, which gets
# sourced after .zshenv, and will reorder your path in such a way that
# installed software such as Ruby, rbenv, Homebrew, etc. may not work
# correctly. You can rename the file to prevent it from editing your
# environment path after changes made in .zshenv:
#
# % sudo mv /etc/{zprofile,zshenv}
#
# https://github.com/thoughtbot/dotfiles/blob/master/README.md#note-for-os-x-el-capitan-users

# homebrew
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# my local .bin path
export PATH=$HOME/.bin:$PATH

# Update package config
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/X11/lib/pkgconfig

# older versions of ruby - ain't no body got time for that
# export RBENV_VERSION=2.4.0

# setup gopath and gobim
export GOPATH="$HOME/Development/golang"
export GOBIN="$HOME/Development/golang/bin"
# export GOROOT="/usr/local/Cellar/go/1.4.2/libexec"
export PATH="$GOBIN:$PATH"

# rbenv (installed via homebrew)
# export RBENV_ROOT=/usr/local/var/rbenv
# export PATH="$(rbenv root)/shims:$(rbenv root)/bin:$PATH"

# nvm (installed via homebrew)
# export NVM_DIR="$HOME/.nvm"
# . "$(brew --prefix nvm)/nvm.sh"

# arc
export PATH="/Users/keithpitt/Development/phacility/arcanist/bin:$PATH"

#chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

alias cya='/System/Library/CoreServices/"Menu Extras"/User.menu/Contents/Resources/CGSession -suspend'
