# Update path
export PATH="$HOME/.rbenv/bin:/usr/local/bin:/usr/local/sbin:$HOME/Development/dotfiles/bin:$PATH"

# Update package config
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/X11/lib/pkgconfig

# Load RBenv
eval "$(rbenv init --no-rehash - zsh)"
