# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export ZSH_THEME="nicoulaj"
# export ZSH_THEME="random"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git rails3 autojump)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin

# Load RVM
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Load scripts
source "$HOME/.scripts/publish_to.sh"

export APPLEDOC_TEMPLATE_PATH="$HOME/Development/appledoc/Templates"
export EDITOR="vim -c 'startinsert'" # Start in insert mode
export PGOPTIONS='-c client_min_messages=WARNING'

export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home"
# export EC2_PRIVATE_KEY="$(/bin/ls $HOME/.ec2/pk-*.pem)"
# export EC2_CERT="$(/bin/ls $HOME/.ec2/cert-*.pem)"
# export EC2_AMITOOL_HOME="/usr/local/Cellar/ec2-ami-tools/1.3-45758/jars"

# Don't auto correct these commands
if [ -f ~/.zsh_nocorrect ]; then
    while read -r COMMAND; do
        alias $COMMAND="nocorrect $COMMAND"
    done < ~/.zsh_nocorrect
fi

# Random shortcuts
alias v='vim'
alias t='tree -C' # Colors by default
alias .='tree -C -L 2; echo "\n\033[32m$PWD"'

# Development
alias be='bundle exec'
alias boom!="git pull --rebase && be rake db:migrate && be rake && git push"
alias boom="boom!"
alias jasmine_consumer='be rake jasmine CONFIG_YML=jasmine_consumer.yml'
alias gogo='if [ -d log ]; then rm -rf log/*.log; fi; bundle && be rake db:migrate && if [ -f Procfile.development ] ; then be foreman start -f Procfile.development; else; be foreman start; fi'
alias testit='if [ -d coverage ]; then rm -rf coverage; fi; bundle && be rake db:migrate && be rake db:test:prepare && be rake'

# Git aliases
alias gaa="git add -A"
alias gd="git diff"
alias gds="git diff --staged"
alias gs="git status --short"
alias glg="git log --graph --pretty=\"format:%C(yellow)%h%Cblue%d%Creset %s %C(white) %an, %ar%Creset\""
alias gm='git merge --no-ff'
alias gmf='git merge --ff-only'
alias grr='git reset HEAD --hard; git clean -fn'

# Ctags
alias ctagsit='ctags -R --exclude=.git --exclude=log --exclude=coverage *'

# Load RBenv
export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
eval "$(rbenv init -)"

# Make the rubies fasterer
export RUBY_HEAP_MIN_SLOTS=1000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=1000000000
export RUBY_HEAP_FREE_MIN=500000
